### ISSUE TITLE
PS2

### ISSUE THREAD

**Issue by ghost** [shugamoe/MACS30200proj#2]
Please upload a PDF document so that I may download it. Thanks.

**Comment by shugamoe** [comment]
It's [there](https://github.com/shugamoe/MACS30200proj/blob/master/ProblemSets/PS2/comp_pset.pdf).

**Comment by ghost** [comment]
I see it now. I'm not sure what happened before. I was only able to see your code. My apologies!

**Comment by shugamoe** [comment]
No worries at all.
